### ISSUE TITLE
cannot update my data

### ISSUE THREAD

**Issue by fsouza** [segue-org/segue#4]
When I try to update my data, I get a 403 error from the API. After editing my data (mini-résumé), I hit the "save changes" button, and using the browser console, I can see the response:

```
HTTP/1.1 403 Forbidden
[...]
{"errors":{"message":"user is not authorized for this action"}}
```

**Comment by fmobus** [comment]
Thanks for the report. The ownership check of modify was affected by the fixes of the previous issues. The problem has now been fixed and covered by tests.

**Comment by fsouza** [comment]
Thanks for fixing it and sorry for the mess with the patch in the first place x)
