### ISSUE TITLE
Arquivos de configuração do ansible faltantes

### ISSUE THREAD

**Issue by jeisoncp** [segue-org/segue#7]
Estava tentando instalar o segue na minha máquina, mas o ansible aponta que o arquivo `ansible/secret/vagrant.yml` não existe.

Pelo que analisei este é um arquivo de variáveis locais, que acredito que deve ser criado por mim. Contudo não sei quais variáveis definir no arquivo. Como devo criá-lo?

Talvez a inclusão de um template ou uma seção no readme documentando isso seja uma sugestão legal.

**Comment by fmobus** [comment]
No momento, o meu vagrant.yml tem as seguintes chaves:

````
pagseguro_email
pagseguro_token
mail_bcc
boleto_convenio
boleto_offset
boleto_tipo_convenio
boleto_carteira
boleto_agencia
boleto_conta
boleto_cnpj
boleto_endereco
boleto_empresa
`````

Em princípio, você poderia criar esse YAML sem nenhuma variável dentro, pois o ansible reclamaria de cada variável não existente na hora que você rodar ele. Existem mais algumas variáveis que você provavelmente deveria fazer *override* para a produção (production.yml) - em especial, as que envolvem segredos ou criptografia. Pelo que eu pude olhar, as variáveis que deveriam ser alteradas para produção seriam pelo menos essas:

````
jwt_secret
dbuser
dbname
dbpass
mail_server
mail_port
mail_sender
mail_user
mail_pass
mail_bcc
mail_use_tls
pagseguro_env
````

No mais, recomendo seguir o desenvolvimento através do *fork* do Ricardo Gerhardt, que está continuando o desenvolvimento do sistema https://github.com/rgerhardt/segue
