### ISSUE TITLE
"undefined" messages when logged in for some days

### ISSUE THREAD

**Issue by mauricioszabo** [segue-org/segue#8]
If I just close the browser tab, without logging out, and some days later try to access the page, it just says "undefined" multiple times and doesn't open anything.

**Comment by fmobus** [comment]
Thanks for your report, but this application is now being maintained elsewhere. Please report this on https://github.com/rgerhardt/segue

**Comment by mauricioszabo** [comment]
There is no "issues" tab on the link you sent me...

![image](https://cloud.githubusercontent.com/assets/138037/14367020/15075f40-fcec-11e5-8b6f-6f64f2a088e3.png)

**Comment by fmobus** [comment]
That's weird. I will ping the current maintainer directly through e-mail and get back to you.
